### ISSUE TITLE
Consider publishing `Kafcat` as `asdf` plugin

### ISSUE THREAD

**Issue by x80486** [rollulus/kafcat#1]
Would be great if `Kafcat` could be [managed](https://github.com/asdf-vm/asdf-plugins/issues/568/) via (the super convenient) `asdf` version management tool :partying_face:

**Comment by rollulus** [comment]
Thanks for your interest but I believe kafcat has become pretty obsolete... [kcat](https://github.com/edenhill/kcat) seems to be the new hotness.

**Comment by x80486** [comment]
I understand; I'll be switching gears then to that one :+1:
